apiVersion: v1
kind: Service
metadata:
  name: fastapi-middleware-service
spec:
  selector:
    app: fastapi-middleware
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
  type: NodePort
